- name: Demo on Loops
  hosts: localhost
  tasks:
    - name: Print Debug with List of Values Loop
      ansible.builtin.debug:
        msg: Fruit Name = {{item}}
      loop:
        - apple
        - banana
        - orange
    - name: Print Debug with List of Maps
      ansible.builtin.debug:
        msg: Fruit Name = {{item.name}}, Quantity = {{item.quantity}}
      loop:
        - { name: "apple", quantity: 100 }
        - { name: "banana", quantity: 200 }
        - { name: "orange", quantity: 50 }